[package]
name = "proposed-traits"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-storage = "0.3.1"
rand_core = "0.6"
async-trait = "0.1.51"
embedded-hal = "1"
embedded-io = "0.6.1"

[[example]]
name = "otp_aspeed"
path = "examples/otp_aspeed.rs"
